version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
        versions:
          - ">=7.0.0"
  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
