apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - app/deployment.yaml
  - app/service.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/prometheus-service.yaml
  - monitoring/grafana-deployment.yaml
  - monitoring/grafana-service.yaml

configMapGenerator:
  - name: prometheus-config
    namespace: observability
    files:
      - prometheus.yml=monitoring/prometheus.yml
  - name: grafana-datasources
    namespace: observability
    files:
      - datasource.yaml=monitoring/grafana/datasource.yaml
  - name: grafana-dashboard-provider
    namespace: observability
    files:
      - dashboard-provider.yaml=monitoring/grafana/dashboard-provider.yaml
  - name: grafana-dashboards
    namespace: observability
    files:
      - devops-assignment.json=monitoring/grafana/devops-assignment-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: devops-home-assignment
