apiVersion: v1
kind: Service
metadata:
  name: devops-assignment
  namespace: app
  labels:
    app.kubernetes.io/name: devops-assignment
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: devops-home-assignment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devops-assignment
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30000
      protocol: TCP
